### PR TITLE
Adding CI for Linux and linters

### PR DESCRIPTION
**Pull request by colin99d**
This PR adds Linux tests and linters (Clippy and Rustfmt). It also looks into adding Windows CI, but currently there appears to be a blocking issue.

### CODE REVIEW

**Comment by GyulyVGC** [comment]
I think this won't run because when running on Linux and Windows you need to specific which dependencies to install in the CI

**Comment by colin99d** [comment]
Yup! I have it in draft to experiment!

**Comment by colin99d** [comment]
@GyulyVGC it looks like if we want to use the Windows CI we will need to make a Npcap OEM account. See here:
https://github.com/rust-pcap/pcap/blob/main/.github/workflows/ci-steps.yml
https://npcap.com/oem/
I am not sure whether this is free or what is required to get one. For now should we ignore windows testing, and maybe get into contact with the npcap team?

**Comment by GyulyVGC** [comment]
Mm, are you sure there is no workaround? 

Have you tried checking WinPcap as an alternative? You could check what [pcap](https://github.com/rust-pcap/pcap/tree/main/.github/workflows) do.

Thanks for your contributions!

**Comment by colin99d** [comment]
https://github.com/nmap/npcap/issues/227

It looks like pcap had success with them in the past. I think for now we should remove the windows tests and put an issue on the npcap repo. If they are willing to work with us it would be much better to have the actual software we are using, rather than create a CI nightmare in the future by relying on incorrect software.

**Comment by GyulyVGC** [comment]
Agreed!

**Comment by GyulyVGC** [comment]
May I ask how the fmt and clippy steps work? If the workflow will fail also if I have introduced a not formatted line in my code I wouldn't like it that much.

**Comment by colin99d** [comment]
Yeah they work as you described. I think they are valuable to have because it forces everyone to format the code before submitting a PR. Since rust makes this super easy `cargo fmt`, and since you can still merge a PR even if an action fails, I don't see the harm. I am working on having clippy ignore the `TCP` => `Tcp` thing right now.

**Comment by GyulyVGC** [comment]
Sounds fair. We can keep them then.

**Comment by colin99d** [comment]
Cool! Let me fix the clippy ignore and remove windows and we should be good. I suggest you leave an issue on NpCap: https://github.com/nmap/npcap, since I don't want to speak on behalf of your project. Also you got a discord or something so we can chat?

**Comment by colin99d** [comment]
Everything on my end is done now!

**Comment by GyulyVGC** [comment]
I still see clippy step failing. If I recall correctly the only warnings I had with clippy were related to camel case things.

**Comment by GyulyVGC** [comment]
Whoops, just noticed the cause, are you able to exclude that check as well?

**Comment by colin99d** [comment]
Yup!

**Comment by colin99d** [comment]
Done!

**Comment by GyulyVGC** [comment]
> [nmap/npcap#227](https://github.com/nmap/npcap/issues/227)
> 
> It looks like pcap had success with them in the past. I think for now we should remove the windows tests and put an issue on the npcap repo. If they are willing to work with us it would be much better to have the actual software we are using, rather than create a CI nightmare in the future by relying on incorrect software.

@colin99d this is just to inform you that today, after a bit of delays on their side, I've finally managed to setup a Windows workflow based on Npcap (#53).
Thanks for the idea!

**Comment by colin99d** [comment]
> > [nmap/npcap#227](https://github.com/nmap/npcap/issues/227)
> > It looks like pcap had success with them in the past. I think for now we should remove the windows tests and put an issue on the npcap repo. If they are willing to work with us it would be much better to have the actual software we are using, rather than create a CI nightmare in the future by relying on incorrect software.
> 
> @colin99d this is just to inform you that today, after a bit of delays on their side, I've finally managed to setup a Windows workflow based on Npcap (#53). Thanks for the idea!

Lets go!!!!! Nice work.

**Pull request merged**
