### PR TITLE
General settings

### LINKED ISSUE #202: Font is comically large
**Describe the bug**
image

(nemo font for comparison)

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.2.12-arch1-1
 - Version: 1.2.0
 - WM: bspwm 0.9.10

I'm not sure what is causing this

### LINKED ISSUE #243: [Feature Request] Option to provide path to own geoip database.
**Is your feature request related to a problem? Please describe.**
To have better ip information accuracy, if you have paid database

**Describe the solution you'd like**
Options like `-geoip-country /path/to/country.mmdb`, `-geoip-asn /path/to/asn.mmdb`

### LINKED ISSUE #291: Customize the report file location
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Please let the report file location to be modified by the user choosing a different path. 

### Is your feature request related to a problem?

The file is constantly updated and people with SSD may want to reduce disk writes. I'd like to change the location to `/tmp` on Linux (the RAM).

### PR DESCRIPTION
**Pull request by GyulyVGC**
As the application is growing, more and more configurations are needed.
The current settings are not enough to cover more advanced customisations: for this reason, advanced settings are being introduced with this PR.

- interface scale factor, useful to zoom in/out the widgets and text of the window (fixes #202 and #344)
- custom paths for MMDBs, to let you use the commercial versions of the country and ASN databases in case you own it (fixes #243)
- path to a TOML file containing a custom theme (related to #286)
- ~custom path for the output report, to find the file more easily or reduce the number of disk writes in case of SSDs~ (this will be implemented while adding support for PCAP generation)

Moreover, this PR introduces the ability to remember the size and position of the application window so that it will reopen with the same window properties.

### CODE REVIEW

**Comment by joshuamegnauth54** [comment]
#243, #291, and [PR #286](https://github.com/GyulyVGC/sniffnet/pull/286) will require file dialogs, right? Have you encountered the [Rusty File Dialogs](https://github.com/PolyMeilex/rfd) crate? It seems like `iced` will [use `rfd` for dialogs](https://github.com/iced-rs/iced/issues/1002) too. You should able to use `rfd` and then minimally change the code when support is officially merged into `iced`. `rfd` is also cross-platform.

Also, I can try to rebase [#286](https://github.com/GyulyVGC/sniffnet/pull/286) onto the simpler custom theme implementation we worked on, if you'd like.

**Comment by GyulyVGC** [comment]
Hey @joshuamegnauth54 thanks for coming back!
I had in mind to tag you once this PR gets merged. 
I implemented the choice of custom MMDB paths and I'll do similarly also for the output report in the next days.
For the moment I'm using simple `TextInput` boxes as you initially did and I'm not planning to integrate `rfd` due to lack of free time, but if you want to, feel free to give it a try.
You can rebase #286 to the branch of this PR and add the option to choose the path in the new Advanced settings page.
Note that in the meantime I also introduced first-class theming in https://github.com/GyulyVGC/sniffnet/pull/339; this means that there is no more the need to pass the `style` attribute everywhere and as a result your code should be way cleaner now.

**Comment by joshuamegnauth54** [comment]
Okay, I'll get to work rebasing today. :smiley_cat:  `TextInput` boxes should be fine for now too.

**Review by GyulyVGC — COMMENTED** [review]
🚢

**Comment by GyulyVGC** [comment]
Hey @joshuamegnauth54 I finally merged to `main` the changes related to custom TOML files for the style.
At the end I placed the text box where you originally placed it (at the bottom of settings style tab).
I applied some nice tricks to make it looks like one of the other standard palettes once the theme is loaded and I'm really happy with the result.
Let me know your thoughts.
Sooner or later I will also add the possibility to open a file dialog through `rfd`.

**Pull request merged**
