### PR TITLE
feat: support --help and --version CLI arguments

### LINKED ISSUE #264: sniffnet doesn't respect `--help` and `--version` flags
**Describe the bug**
Running `sniffnet --help` or `sniffnet --version` should display information in the terminal without starting the GUI.

**To Reproduce**
1. Run `sniffnet --help` or `sniffnet --version`

**Expected behavior**
The GUI should not start.

`sniffnet --help` should show what CLI flags are supported (it should support at least `--help` and `--version`).

`sniffnet --version` should display the current version.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.2.1

### PR DESCRIPTION
**Pull request by Aloso**
This adds `--help`/`-h` and `--version`/`-V` CLI arguments, following the defaults used by [clap](https://docs.rs/clap/latest/clap/). When any of these options is found, we exit with status code 0, which indicates success. When an unknown argument is supplied, we exit with the status code 1. Arguments after `--help`/`--version` are ignored, which I think is not a big deal.

If the plan is to support more CLI arguments, it would make sense to switch to a proper argument parser like clap or [lexopt](https://docs.rs/lexopt/).

Closes #264

### CODE REVIEW

**Comment by GyulyVGC** [comment]
I think it's better to not include `clap` just for these two arguments, as you did.
I originally thought to also implement https://github.com/GyulyVGC/sniffnet/issues/243 through CLI arguments, but in the end I think I'll implement it as a feature directly inside the GUI for ease of the users.

Seems fine to me, I will test it as soon as I have time to do so.
Just a little notice is that we could also include `-v` in lowercase (I've seen it more often lowercase wrt uppercase).

**Comment by Aloso** [comment]
@GyulyVGC sure, I'll add `-v` as well.

Regarding the geoip database, another option is to use an environment variable, e.g.

```sh
SNIFFNET_GEOIP_COUNTRY=/path/to/country.mmdb sniffnet
```

which can be added to a shell config file for convenience.

**Comment by GyulyVGC** [comment]
I'm already using [confy](https://docs.rs/confy/latest/confy/) to save configurations for the app (settings info and last successfully sniffed adapter) and I was thinking to adopt the same approach.

**Review by GyulyVGC — APPROVED** [review]

**Comment by GyulyVGC** [comment]
@all-contributors please add @Aloso for code.

**Pull request merged**
