### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by acolombier**
Answering to the call in the issue #60, this PR adds translation for french.

Worth to mention that although native speaker, it has been a few years I have written my own language in a formal way, so if there is any fellow french speakers that could help review it, that would be massively appreciated!

### CODE REVIEW

**Comment by GyulyVGC** [comment]
That's amazing! 
If you know other French people you could ask directly to them to give it a look. However, if you speak French don't worry too much about the level of formalism, your translation will be surely good enough!

**Review by GyulyVGC — COMMENTED** [review]
I know nothing about French, but it seems to me that the last phrase refers to "minutes" instead of "notifications"

**Comment by acolombier** [comment]
You're correct - thanks for catching that! Should be updated now.

**Comment by GyulyVGC** [comment]
Thanks a lot for the translation, now all checks pass and everything seems good.
I will do the last graphical checks on the GUI and then the PR will be merged.

**Review by Katew212 — COMMENTED** [review]
[Y]()

**Pull request merged**
