### PR TITLE
Adding Some Tests and Ran `cargo fmt`

### PR DESCRIPTION
**Pull request by colin99d**
Hello,

I was looking to add some tests and get your feedback on where you wanted testing added most, but then I ran cargo fmt and and that reformatted a bunch of code. I could add some Github CI over the formatting if you like.

### CODE REVIEW

**Comment by GyulyVGC** [comment]
Don't worry for the formatting. I will do `cargo fmt` on my local copy without merging yours.

Thank you very much for the tests instead! Even if the tests you wrote are pretty trivial, it's still nice having them.

I would like to be able to test more the sniffing process, but this could be hard.

Another useful thing to do is to update the [workflow](https://github.com/GyulyVGC/sniffnet/blob/main/.github/workflows/rust.yml) including on Windows and Linux and their respective dependencies.

**Comment by colin99d** [comment]
Would you like me to remove the cargo fmt stuff real quick?

**Comment by GyulyVGC** [comment]
> Would you like me to remove the cargo fmt stuff real quick?

That'd be awesome, thanks!

**Comment by colin99d** [comment]
Done!

**Pull request merged**
