### PR TITLE
Add German translations

### PR DESCRIPTION
**Pull request by luca3s**
Should be mostly correct. In a few spots (e.g. Deleting Notifications or quitting analysis) the pop-up window is a bit small for the longer German text, so it looks a bit weird.

### CODE REVIEW

**Comment by GyulyVGC** [comment]
Thank you very much! 
Don't worry about text longer than the view, I'll fix it if needed.

**Comment by GyulyVGC** [comment]
I've reviewed everything and added some fixes here and there. 
Let me know if everything is fine for you as well!

**Comment by luca3s** [comment]
Yes thank you the pop-up windows look nice now.

**Review by GyulyVGC — APPROVED** [review]

**Comment by GyulyVGC** [comment]
@all-contributors please add @luca3s for translation.

**Pull request merged**
